name: oce_poc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.1.0
  permission_handler: ^11.3.0
  image_cropper: ^5.0.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
